//
//
//    def GetTracks(self,
//                  trackSip3dSig,
//                  trackSip3dVal,
//                  trackSip2dSig,
//                  trackSip2dVal,
//                  trackDecayLenVal,
//                  trackJetDistVal,
//                  trackJetDistSig,
//                  trackPtRel,
//                  trackMomentum,
//                  trackEta,
//                  trackPhi,
//                  trackPPar,
//                  trackDeltaR,
//                  trackPtRatio,
//                  trackPParRatio,
//                  trackChi2,
//                  trackNTotalHits,
//                  trackNPixelHits,
//              ):
//
//        self.tracks    = []
//        for iTrack in range(len(trackSip3dSig)):
//            self.tracks.append(TrackData(trackSip3dSig[iTrack],
//                                         trackSip3dVal[iTrack],
//                                         trackSip2dSig[iTrack],
//                                         trackSip2dVal[iTrack],
//                                         trackDecayLenVal[iTrack],
//                                         trackJetDistVal[iTrack],
//                                         trackJetDistSig[iTrack],
//                                         trackPtRel[iTrack],
//                                         trackMomentum[iTrack],
//                                         trackEta[iTrack],
//                                         trackPhi[iTrack],
//                                         trackPPar[iTrack],
//                                         trackDeltaR[iTrack],
//                                         trackPtRatio[iTrack],
//                                         trackPParRatio[iTrack],
//                                         trackChi2[iTrack],
//                                         trackNTotalHits[iTrack],
//                                         trackNPixelHits[iTrack],
//                                         jet = self,
//                                     ))
